name: PE Offices
favicon: null
layout_spectrum: 0.35132
typography_spectrum: 0.47556
title: PE - Your Whole Office Solution Provider
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a5482'
    - '#ffffff'
    - '#000000'
    - '#c8c9cb'
    - '#6189a9'
  brandStrength: 0.5
  lightness: 0.7697508172132075
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
