name: PE Offices
favicon: null
layout_spectrum: 0
typography_spectrum: 0.47556
title: PE - Your Whole Office Solution Provider
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b5481'
    - '#ffffff'
    - '#d0dee5'
    - '#829db2'
    - '#507795'
  brandStrength: 0.8125
  lightness: 0.7697508172132075
  saturation: 0.4375
  rhythmicContrast: 0.49931633099913597
purpose: []
